# You can use coments 
# this is single line comment
# A commented block is skipped during execution

DATABASE_CREDENTIALS:
    Host: containers-us-west-195.railway.app
    Dbname: railway
    user: postgres
    port: 5836
    password: ****************QgUE

TABLE_NAME:
    - table_example

# SQL Language Data Types: https://www.postgresql.org/docs/current/datatype.html
NEW_TABLE_COLUMNS:
    crop: varchar 
    plot: int NOT NULL         
    range: int                   
    entry: int                  
    rep: int         
    treatment: varchar 
    id_observation: varchar PRIMARY KEY 
    observation_name: varchar 
    experiment_name: varchar 
    sampling_identifier: varchar
    variable_name: varchar
    season: varchar
    variable_value: real
    date: date
    
PRIMARY_KEY_COLUMN:
    - id_observation

NEW_COLUMNS_IF_TABLE_EXISTS:
    variable_units: varchar

FILE_TO_UPLOAD:
    folder : ./et_output/
    input_data_file_name : data_file_to_upload.csv