# You can use coments 
# this is single line comment
# A commented block is skipped during execution

FILES_TO_PROCESS: 
    Folder: ./et_files_to_process/
    # Folder: ./et_files_to_process/ACRE/        This is an example of how to use comments 

ADDITIONAL_INFORMATION_FILES: 
    Folder: ./et_additional_information_files/

OUTPUT_FILE_NAME:
    - height_ACRE_Biomass_summer-2022_clean

JOIN_FILES_COMMON_COLUMNS: 
    - Plot
    - Treatment
    - Rep

COLUMNS_TO_DROP:
    - pictureofplot
    - PictureOfexperiment
    - picture_Plot
    - picture_Experiment
    - notes_Plot
    - Width (cm)

UPDATE_COLUMN_NAMES: 
    measurment: Variable_name
    experiment: experiment_name
    Date Of Measurement: date
    height(cm): Variable_value
    heigth(cm): Variable_value
  
NEW_COLUMNS:
    Variable_units: cm
    Crop : Wheat 

# Make sure to replace extra /t characters 
UPDATE_COLUMN_VALUES:
    a: A
    b: B
    c: C
    d: D
    Early: Early planting date
    Late: Late planting date
    ACRE-Biomass: ACRE Public Biomass
    y22: 2022
    LAI: Leaf Area Index

CREATE_PRIMARY_KEY_IF_NEEDED:
    # id_observation:
        # - Plot
        # - Experiment
        # - Treatment
        # - Season
        # - Variable_name
        # - Date
        
PRIMARY_KEY_COLUMN:
  - id_observation

UPDATE_PRIMARY_KEY_VALUES:
    width-height: height
    sampl: sampling